export const posts = [
  {
    id: 1,
    screenName: "Darren Pereira",
    userName: "@Daz_Attack",
    title: "What happened to Liverpool last night?",
    time: "5m ago",
    location: "Hounslow, London",
    likes: 5,
    comments: 1,
    profilePic: require("../../images/DarrenPereira.jpg"),
  },
  {
    id: 2,
    screenName: "Jack Brook",
    userName: "@JB97",
    title: "Come on you Bees!",
    time: "10m ago",
    location: "Brentford, London",
    with: "Aaron DaCosta",
    likes: 10,
    comments: 3,
    profilePic: require("../../images/JackBrook.jpg"),
  },
  {
    id: 3,
    screenName: "London News",
    userName: "@LondonNews",
    title: "Rounding up today's top stories",
    time: "10m ago",
    location: "White City, London",
    likes: 50,
    comments: 27,
    profilePic: require("../../images/LondonNews.jpg"),
  },
  {
    id: 4,
    screenName: "Allana Ed Peacock",
    userName: "@APeacock",
    title: "You Won't believe what happened to me today!",
    time: "12m ago",
    location: "Bristol",
    likes: 13,
    comments: 3,
    profilePic: require("../../images/Allana.jpg"),
  },
  {
    id: 5,
    screenName: "Silvia Ian",
    userName: "@siian",
    title: "My review of Pétrus by Gordon Ramsay",
    time: "15m ago",
    location: "",
    likes: 20,
    comments: 14,
    profilePic: require("../../images/Silvia.jpg"),
  },
  {
    id: 6,
    screenName: "Sandra Tria",
    userName: "@STria99",
    title: "ASMR daily",
    time: "23m ago",
    location: "Seven Dials, Brighton",
    likes: 6,
    comments: 2,
    profilePic: require("../../images/Sandra.jpg"),
  },
  {
    id: 7,
    screenName: "Kermit Marylyn",
    userName: "@Kerma",
    title: "Thoughts on this melody?",
    time: "28m ago",
    location: "Salford, Manchester",
    likes: 15,
    comments: 8,
    profilePic: require("../../images/Kermit.jpg"),
  },
  {
    id: 8,
    screenName: "Malcolm Kemp",
    userName: "@MKemp",
    title: "Listen to this!",
    time: "33m ago",
    location: "",
    likes: 4,
    comments: 1,
    profilePic: require("../../images/Malcolm.jpg"),
  },
  {
    id: 9,
    screenName: "Vince Ted",
    userName: "VT22",
    title: "Daily motivation",
    time: "45m ago",
    location: "Newcastle upon Tyne",
    likes: 11,
    comments: 3,
    profilePic: require("../../images/VinceTed.jpg"),
  },
  {
    id: 10,
    screenName: "Clarence Ellington",
    userName: "@clazell97",
    title: "Thoughts on the VOYCE app so far",
    time: "1h ago",
    location: "Stourbridge, Birmingham",
    likes: 13,
    comments: 3,
    profilePic: require("../../images/Clarence.jpg"),
  },
];
